### ISSUE TITLE
All DB readonly

### ISSUE THREAD

**Issue by EvgeniyDoctor** [linuxserver/docker-sqlitebrowser#7] opened 2023-05-12 22:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every database that i have tried to edit was "readonly". From another similar program for editing sqlite db in docker i edited my table without any problem. Of course, all my db had 777 rights and respectful owner for this test (externally). Internal:
`
-rwxrwxrwx 1 1026 messagebus 11558912 May 12 21:44 db.db
`
this is default, i did not touch it.
As always, your image is absolutely unusable, linuxserver. And as always, you will do nothing to fix it. But i will provide more information anyway.

### Expected Behavior

Database should not be readonly.

### Steps To Reproduce

Try to edit 1 database at least... Try testing your images first!

### Environment

```markdown
- OS: DSM 6
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:3.12.2
    container_name: sqlite
    environment:
      PUID: 1026
      PGID: 65539
      CUSTOM_USER: "admin"
      PASSWORD: "admin"
      FM_HOME: /data
    volumes:
      - /config:/config:rw
      - /data:/data/subdir1:rw
    ports:
      - 3000:3000
    restart: unless-stopped
```
```


### Container logs

```bash
Why? You will ignore this issue anyway.


[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
DB Browser for SQLite: https://www.patreon.com/db4s

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1026
User GID:    65539
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
Openbox-Message: Failed to open the display from the DISPLAY environment variable.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.1.0 - built Apr 29 2023 18:51:48
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

Obt-Message: Xinerama extension is not present on the server
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
 2023-05-12 22:13:44,531 [INFO] websocket 0: got client connection from 127.0.0.1
 2023-05-12 22:13:44,557 [PRIO] Connections: accepted: @172.28.0.1_1683929624.532791::websocket
```
```

**Comment by aptalca** [comment] 2023-05-12 23:56
Sigh. . .

> As always, your image is absolutely unusable, linuxserver. And as always, you will do nothing to fix it. But i will provide more information anyway.

I use this image occasionally (with emby and plex databases) and it has worked with no issues every time.

> Try to edit 1 database at least... Try testing your images first!

I did, thank you very much.

It really doesn't sound like you're here with good intentions. I'm honestly not feeling inclined to go out of my way to do additional testing at this point.

I'll just leave this comment here as a simple `it works for me`

**Comment by feranwq** [comment] 2023-05-16 18:32
I solved this problem by mounting the data file to the /config directory
```
    volumes:
      - ./sqlitebrowserdata:/config
      - ./appdata/data/db.sqlite3:/data/db.sqlite3
```

then your work is meaningful and saves us a lot of time, thanks

**Comment by aptalca** [comment] 2023-05-16 18:45
You do not have to mount it to `/config` (actually, don't mount it to config unless you don't mind the ownership of the file to potentially change). We chown the config folder.

You can mount it elsewhere, but you need to make sure the perms are correct (set the PUID/PGID accordingly).

If you want to use the container in an ephemeral manner for occasional edits to db files, you can spin it up without bind mounting the config folder and just bind mounting the db file, and setting the PUID/PGID to match the db file.

Closing as this is not a bug and likely pebcak.

OP can utilize discord or discourse for further assistance.

Based on the comment `As always, your image is absolutely unusable, linuxserver` it is safe to assume OP is having larger issues with their system independent of this specific container.

**Closed by aptalca** 2023-05-16 18:45 UTC

**Comment by AliM1988** [comment] 2024-07-24 23:03
For other users that face with this issue, can simply set PUID,PGUID = 0 (the root user usually has a UID and GID of 0).
See [more info](https://docs.linuxserver.io/general/understanding-puid-and-pgid/#why-use-these).

**Comment by AliM1988** [comment] 2024-12-05 22:59
```
    environment:
      - PUID=0          # use 0 for root (run command 'id' in terminal to see: uid=0(root))
      - PGID=0          # use 0 for root (run command 'id' in terminal to see: gid=0(root))
```
